# Generated by Django 5.1.7 on 2025-05-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
