# Generated by Django 5.1.7 on 2025-05-23 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_agent_contact_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='owner_agent_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
