# Generated by Django 5.1.7 on 2025-05-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_property_owner_agent_contact_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner_agent_name',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='property',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_agent_contact_no',
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('5_MARLA', '5 Marla'), ('7_MARLA', '7 Marla'), ('10_MARLA', '10 Marla'), ('1_KANAL', '1 Kanal')], max_length=20, null=True),
        ),
    ]
